site_name: Spatial Computing Project - Group 2

nav:
  - Home: "index.md"
  - Planning: # "a1_planning.md"
      - Process: "a1.1_Process.md"
      - Products: "a1.1_Product.md"
  - Configuring: #"a2_configuring.md"
      - Process: "a2.1_Process.md"
      - Products: "a2.1_Product.md"
      - Notebook W1: "notebooks/placeholder_w1_Notebook.md"
  - Massing: #"a3_massing.md"
      - Process: "a3.1_Process.md"
      - Products: "a3.1_Product.md"
      - Notebooks:
        - Notebook W2: "notebooks/placeholder_w2_Notebook.md"
        - Notebook W3: "notebooks/placeholder_w3_Notebook.md"
  - Forming: #"a4_forming.md"
      - Process: "a4.1_Process.md"
      - Products: "a4.1_Product.md"
  - About: "about.md"
  - Index:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  palette:
    primary: red
  features:
    - search


markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji

plugins:
  - search
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false
  - git-revision-date-localized