site_name: Spatial Computing Project - Zoho’s Pearl

nav:
  - Home: "index.md"
  - Planning: # "a1_planning.md"
      - Process: "a1.1_Process.md"
      - Products: "a1.1_Product.md"
  - Configuring: #"a2_configuring.md"
      - Process: "a2.1_Process.md"
      - Products: "a2.1_Product.md"
      - Notebook 1: "a2.2_Notebook1.md"
  - Massing: #"a3_massing.md"
      # - Process: "a3.1_Process.md"
      # - Products: "a3.1_Product.md"
      - Notebook 2: "a3.2_Notebook2.md"
      - Notebook 4: "a3.2_Notebook4.md"
  - Forming: #"a4_forming.md"
      # - Process: "a4.1_Process.md"
      # - Products: "a4.1_Product.md"
      - Notebook 5: "a4.2_Notebook5.md"
      - Notebook 6: "a4.2_Notebook6.md"
      - Results: "a4.2_Results.md"
  - About: "about.md"
  - Index:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  palette:
    primary: red
  features:
    - search


markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist

plugins:
  - search
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false
  - git-revision-date-localized